version: "3"
services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    labels:
      - traefik.enable=false
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "9080:80"   # live traffic
      - "9880:8080" # admin UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
